version: '3.8'

services:
  client:
    build:
      context: client
      dockerfile: .dockerFile
    ports:
      - "8080:8080"
    environment:
      - VUE_APP_BACKEND_URL=http://localhost:5000
    volumes:       
      - ./client/src:/app/src
      - ./client/public:/app/public
    depends_on:
      - server
  server:
    build:
      context: server
      dockerfile: .dockerFile
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongo:27017/mydatabase
    volumes:       
      - ./server/app:/app/app

  mongo:
    image: mongo
    ports:
      - "27017:27017"
